# Generated by Django 6.1.1 on 2026-09-27 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=150)),
                ('acao', models.CharField(choices=[('create', 'Criação'), ('update', 'Edição'), ('delete', 'Exclusão')], max_length=10)),
                ('app_label', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('objeto_repr', models.CharField(max_length=255)),
                ('detalhes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_alteracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de alteração',
                'verbose_name_plural': 'Logs de alterações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
