# Generated by Django 5.2.17 on 2026-09-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='materiais.material')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'Item do orçamento',
                'verbose_name_plural': 'Itens do orçamento',
            },
        ),
    ]
